name: label action
on:
  label: 
    types: [created]
jobs:
  sample-label-action:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "haad_ref: ${{ github.head_ref }}"
      - run: echo "ref: ${{ github.ref }}" 
